"use client";

import { ExecutiveBriefing } from "../types";
import { 
  Card, 
  CardContent, 
  CardHeader, 
  CardTitle 
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  Sparkles, 
  AlertTriangle, 
  Lightbulb, 
  TrendingUp, 
  ArrowRight,
  ShieldCheck,
  Zap
} from "lucide-react";
import { Button } from "@/components/ui/button";

export function ExecutiveBriefingPanel({ briefing }: { briefing: ExecutiveBriefing }) {
  return (
    <div className="space-y-6">
      <Card className="bg-gradient-to-br from-primary/10 via-background to-background border-primary/20 shadow-2xl shadow-primary/5">
        <CardHeader className="flex flex-row items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-xl bg-primary/20 flex items-center justify-center animate-pulse">
              <Sparkles className="h-5 w-5 text-primary" />
            </div>
            <div>
              <CardTitle className="text-xl font-bold tracking-tight">AI Strategic Briefing</CardTitle>
              <p className="text-xs text-muted-foreground">Generated by Nexus Intelligence v2.4</p>
            </div>
          </div>
          <Badge className={briefing.sentiment === 'BULLISH' ? 'bg-emerald-500/10 text-emerald-500 border-emerald-500/20' : 'bg-orange-500/10 text-orange-500 border-orange-500/20'}>
            <TrendingUp className="mr-1 h-3 w-3" />
            {briefing.sentiment} Outlook
          </Badge>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="p-6 rounded-2xl bg-card/30 border border-primary/5 backdrop-blur-sm">
            <p className="text-sm leading-relaxed text-foreground/90 italic font-medium">
              "{briefing.summary}"
            </p>
          </div>

          <div className="grid gap-6 md:grid-cols-2">
            {/* Critical Alerts */}
            <div className="space-y-4">
              <h3 className="text-xs font-bold uppercase tracking-widest text-orange-500 flex items-center gap-2">
                <AlertTriangle className="h-3 w-3" />
                Operational Anomalies
              </h3>
              <div className="space-y-2">
                {briefing.criticalAlerts.map((alert, i) => (
                  <div key={i} className="flex items-start gap-3 p-3 rounded-lg bg-orange-500/5 border border-orange-500/10 text-xs">
                    <ShieldCheck className="h-4 w-4 text-orange-500 shrink-0" />
                    <span>{alert}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* AI Recommendations */}
            <div className="space-y-4">
              <h3 className="text-xs font-bold uppercase tracking-widest text-primary flex items-center gap-2">
                <Lightbulb className="h-3 w-3" />
                Strategic Actions
              </h3>
              <div className="space-y-2">
                {briefing.recommendations.map((rec, i) => (
                  <div key={i} className="flex items-start justify-between gap-3 p-3 rounded-lg bg-primary/5 border border-primary/10 group hover:border-primary/30 transition-all cursor-pointer">
                    <div className="space-y-1">
                      <p className="text-xs font-bold">{rec.title}</p>
                      <p className="text-[10px] text-muted-foreground">{rec.description}</p>
                    </div>
                    <Button variant="ghost" size="icon" className="h-6 w-6 group-hover:bg-primary group-hover:text-white">
                      <ArrowRight className="h-3 w-3" />
                    </Button>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
